RSG = {}

RSG.WelcomeText = "WELCOME TO RSG FRAMEWORK"

RSG.Texts = {
    Body = "Cuerpo",
    Face = "Cara",
    Hair_beard = "Pelo y Barba",
    HairStyle = "Estilo de pelo",
    HairColor = "Color de pelo",
    BeardStyle = "Estilo de barba",
    BeardColor = "Color Barba",
    Makeup = "Maquillaje",
    Appearance = "Apariencia",
    Slim = "Delgado",
    Sporty = "Deportivo",
    Medium = "Medio",
    Fat = "Gordo",
    Strong = "Fuerte",
    FaceWidth = "Ancho de cara",
    SkinTone = "Tono de piel",
    Eyes = "Ojos",
    Eyelids = "Párpados",
    Eyebrows = "Cejas",
    Nose = "Nariz",
    Mouth = "Boca",
    Teeth = "Dientes",
    Cheekbones = "Pómulos",
    Jaw = "Mandíbula",
    Ears = "Orejas",
    Chin = "Mentón",
    Defects = "Defectos",
    Hair = "Cabello",
    Beard = "Barba",
    Type = "Tipo",
    Visibility = "Visibilidad",
    ColorPalette = "Paleta De Colores ",
    ColorFirstrate = "Color de primera categoría",
    Eyebrow = "Cejas",
    NoseCurvature = "Curvatura de la nariz",
    UP_DOWN = "UP / DOWN",
    left_right = "left / right",
    UpperLipHeight = "Upper Lip Height",
    UpperLipWidth = "Upper Lip Width",
    UpperLipDepth = "Upper Lip Depth",
    LowerLipHeight = "Lower Lip Height",
    LowerLipWidth = "Lower Lip Width",
    LowerLipDepth = "Lower Lip Depth",
    Make_up = "Make-up",
    Older = "Older",
    Scars = "Type Scars",
    Freckles = "Type Freckles",
    Moles = "Moles",
    Disadvantages = "Disadvantages",
    Spots = "Spots",
    Shadow = "Shadow",
    ColorShadow = "Color Shadow",
    ColorFirst_Class = "Color First-Class Delusion",
    Blushing_Cheek = "Blushing Cheek",
    blush_id = "Cheek Blush Color",
    blush_c1 = "Color First Degree Cheek Redness",
    Lipstick = "Type Lipstick",
    ColorLipstick = "Color Lipstick",
    lipsticks_c1 = "First-Class Color Lipstick",
    lipsticks_c2 = "Second Color Lipstick",
    Eyeliners = "Eyeliners",
    eyeliners_id = "Color Eyeliners",
    eyeliners_c1 = "Color main Eyeliners",
    save = "Save",
    Options = "Options",
    align = "top-left",
    Style = "Style ",
    Color = "Color ",
    Size = "Size",
    Width = "Width ",
    Height = "Height",
    Depth = "Depth",
    Waist = "Waist",
    Chest = "Chest",
    Distance = "Distance",
    Angle = "Angle",
    Clarity = "Clarity",
    Color1 = "<img src='nui://rsg-appearance/img/skin1.png' height='20'>",
    Color2 = "<img src='nui://rsg-appearance/img/skin2.png' height='20'>",
    Color3 = "<img src='nui://rsg-appearance/img/skin3.png' height='20'>",
    Color4 = "<img src='nui://rsg-appearance/img/skin4.png' height='20'>",
    Color5 = "<img src='nui://rsg-appearance/img/skin5.png' height='20'>",
    Color6 = "<img src='nui://rsg-appearance/img/skin6.png' height='20'>",
}
