RSG = {}

RSG.WelcomeText = "WELCOME TO RSG FRAMEWORK"

RSG.Texts = {
    Body = Lang:t('text.body'),
    Face = Lang:t('text.face'),
    Hair_beard = Lang:t('text.beard'),
    HairStyle = Lang:t('text.hair_style'),
    HairColor = Lang:t('text.hair_color'),
    BeardStyle = Lang:t('text.beard_style'),
    BeardColor = Lang:t('text.beard_color'),
    Makeup = Lang:t('text.makeup'),
    Appearance = Lang:t('text.appearance'),
    Slim = Lang:t('text.slim'),
    Sporty = Lang:t('text.sporty'),
    Medium = Lang:t('text.medium'),
    Fat = Lang:t('text.fat'),
    Strong =  Lang:t('text.strong'),
    FaceWidth =  Lang:t('text.face_width'),
    SkinTone = Lang:t('text.skin_tone'),
    Eyes = Lang:t('text.eyes'),
    Eyelids = Lang:t('text.eyelids'),
    Eyebrows =  Lang:t('text.eyebrows'),
    Nose = Lang:t('text.nose'),
    Mouth = Lang:t('text.mouth'),
    Teeth = Lang:t('text.teeth'),
    Cheekbones = Lang:t('text.cheekbones'),
    Jaw = Lang:t('text.jaw'),
    Ears = Lang:t('text.ears'),
    Chin = Lang:t('text.chin'),
    Defects = Lang:t('text.defects'),
    Hair = Lang:t('text.hair'),
    Beard = Lang:t('text.beard'),
    Type = Lang:t('text.type'),
    Visibility = Lang:t('text.visibility'),
    ColorPalette = Lang:t('text.color_palette'),
    ColorFirstrate =  Lang:t('text.color_first_rate'),
    Eyebrow = Lang:t('text.eyebrow'),
    NoseCurvature = Lang:t('text.nose_curvature'),
    UP_DOWN = Lang:t('text.up_down'),
    left_right = Lang:t('text.left_right'),
    UpperLipHeight = Lang:t('text.upper_lip_height'),
    UpperLipWidth = Lang:t('text.upper_lip_width'),
    UpperLipDepth = Lang:t('text.upper_lip_depth'),
    LowerLipHeight = Lang:t('text.lower_lip_height'),
    LowerLipWidth = Lang:t('text.lower_lip_width'),
    LowerLipDepth =  Lang:t('text.lower_lip_depth'),
    Make_up = Lang:t('text.make_up'),
    Older = Lang:t('text.older'),
    Scars = Lang:t('text.type_scars'),
    Freckles = Lang:t('text.type_freckles'),
    Moles = Lang:t('text.moles'),
    Disadvantages = Lang:t('text.disadvantages'),
    Spots = Lang:t('text.spots'),
    Shadow = Lang:t('text.shadow'),
    ColorShadow = Lang:t('text.color_shadow'),
    ColorFirst_Class = Lang:t('text.color_first_class_delusion'),
    Blushing_Cheek = Lang:t('text.blushing_cheek'),
    blush_id = Lang:t('text.cheek_blush_color'),
    blush_c1 = Lang:t('text.color_first_degree_cheek_redness'),
    Lipstick = Lang:t('text.type_lipstick'),
    ColorLipstick = Lang:t('text.color_lipstick'),
    lipsticks_c1 = Lang:t('text.first_class_color_ipstick'),
    lipsticks_c2 = Lang:t('text.second_color_lipstick'),
    Eyeliners = Lang:t('text.eyeliners'),
    eyeliners_id = Lang:t('text.color_eyeliners'),
    eyeliners_c1 = Lang:t('text.color_main_eyeliners'),
    save = Lang:t('text.save'),
    Options = Lang:t('text.options'),
    align = Lang:t('text.top_left'),
    Style = Lang:t('text.style'),
    Color = Lang:t('text.color'),
    Size = Lang:t('text.size'),
    Width = Lang:t('text.width'),
    Height = Lang:t('text.height'),
    Depth = Lang:t('text.depth'),
    Waist = Lang:t('text.waist'),
    Chest = Lang:t('text.chest'),
    Distance = Lang:t('text.distance'),
    Angle = Lang:t('text.angle'),
    Clarity = Lang:t('text.clarity'),
    Color1 = "<img src='nui://rsg-appearance/img/skin1.png' height='20'>",
    Color2 = "<img src='nui://rsg-appearance/img/skin2.png' height='20'>",
    Color3 = "<img src='nui://rsg-appearance/img/skin3.png' height='20'>",
    Color4 = "<img src='nui://rsg-appearance/img/skin4.png' height='20'>",
    Color5 = "<img src='nui://rsg-appearance/img/skin5.png' height='20'>",
    Color6 = "<img src='nui://rsg-appearance/img/skin6.png' height='20'>",
}
